include:
  - project: 'skale-5/gitlab-ci'
    ref: main
    file: '/templates/workflows/.gitlab-ci.common.yml'


# RENOVATE

include:
  - remote: https://gitlab.com/renovate-bot/renovate-runner/-/raw/v12.14.1/templates/renovate.gitlab-ci.yml

renovate:
  # Required if your runners does not support untagged jobs
  #tags:
  #  - renovate
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_ACTION == "renovate"'
